sudo: required
services:
  - docker

before_install:
  - docker build -t dyegomaas/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dyegomaas/react-test npm test -- --coverage

after_success:
  - docker build -t dyegomaas/complex-client ./client
  - docker build -t dyegomaas/complex-server ./server
  - docker build -t dyegomaas/complex-worker ./worker
  - docker build -t dyegomaas/complex-nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push dyegomaas/complex-client
  - docker push dyegomaas/complex-server
  - docker push dyegomaas/complex-worker
  - docker push dyegomaas/complex-nginx